# fly.toml app configuration file generated for spellbackend on 2025-08-10T15:56:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spellbackend'
primary_region = 'sin'

[build]
  dockerfile = "dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "sqlite_data"
  destination = "/database"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
