"""MOE (Singapore) Primary 2-6 Chinese character lesson data: raw
识读字/识写字 lists per lesson (sourced from the official 2024
"欢乐伙伴2.0" syllabus for P2, and the 2015 "欢乐伙伴" syllabus for
P3-P6), plus a generated pinyin+meaning gloss for every unique
character across all five grades.

Pinyin was generated with pypinyin; meanings were pulled from
CC-CEDICT and picked to match the generated pinyin reading, with
manual overrides for characters where the automatic pick was an
obscure/archaic CEDICT sense, a proper noun, or a classifier gloss
that didn't read well as a short kid-facing gloss. See
seed_moe_p1.py for the P1 data/format this generalizes from.
"""

# Chinese numerals for lesson numbers 1-19 (grades use a subset).
CJK_LESSON_NUM = [
    None, "一", "二", "三", "四", "五", "六", "七", "八", "九", "十",
    "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九",
]

# (term: "上"/"下", lesson_number, 识读字 string, 识写字 string)
GRADE_LESSONS = {
    "P2": [
        ("上", 1, "外美丑新卖加亲过现些造试年读级班折帮专助", "外亲兄合很出对年专听"),
        ("上", 2, "吉利岁平余全除贴福时表演舞龙婆拜着您接卷真", "平全家花时龙拿说身业"),
        ("上", 3, "碗盘叉筷杯壶客送主递汽忙骨伸尝原各定第捉非", "杯送主汽把朋友耳舌各非常"),
        ("上", 4, "棵树剪排林形角然拉森从众颜共页空彩蓝绿黄想", "片林色共页太阳云朵红"),
        ("上", 5, "音室哪顶楼术旁向就往转操运路远迷坡久答已经", "音边向足往运动奶从笑"),
        ("上", 6, "骑脚踏应该行桥等停才灯亮邻居互相光照丽极", "坐校走行才安光美丽跑"),
        ("上", 7, "茶糖炒油炸冰温咖啡队找座位特别餐闻味食分懂", "饭青星期香进物分完"),
        ("上", 8, "医病护顾贩教种姨员消防灾灭保抓怕建住", "爷卖种员发坏抓怕房住"),
        ("上", 9, "阴晴湿冷热暗乌闪刮记得窗忘急铃响摸淋呢", "乌电闪风带伞放问忘记"),
        ("上", 10, "蚂蚁爬蜜蜂丛池枝跳清蛙害情让像窝结掉泥成", "飞鱼请鸟叶捉地方喜欢"),
        ("下", 11, "纸机块跟棋搭积布娃吧器许绳捏拼船更鹰追", "过机吗块跟跳象石更"),
        ("下", 12, "永轻命百健康幸愿吹糕首张卡影票礼厅奇怪活宝", "永远百岁吹卡写想宝"),
        ("下", 13, "梁睡觉羽乖总聪金漂吐宠岛欺负丢梦圆迎识醒", "猫爱狗总医丢那兔前"),
        ("下", 14, "难易粗细抢推讨厌争吵弄破撞倒伤容能晶道虹", "难易争吵伤笔容作草"),
        ("下", 15, "茄紫番芽扁玉比伯萝卜煮鼠或者猪拔摘挖考根实", "黄菜扁瓜甜比哭黑考"),
        ("下", 16, "持静绘趣借次英遍架箱盒案附近满始样候知指", "声话借次首英故事样具"),
        ("下", 17, "逛夜市烤肠翅射碰饮料踢等但闹摊阵引群套圈", "夜市炸鸡球楼灯排"),
        ("下", 18, "馆院植海岸参观野泳沙捡壳区处街整齐离城", "海步游泳区现处树净"),
        ("下", 19, "浇桶厕所告诉珍惜滴约断猜摇渴低", "洗冲告诉活连忙凉脸"),
    ],
    "P3": [
        ("上", 1, "科将当司希望军卫练努愿实篇复取举翻页", "当为练习努记总实现件样读"),
        ("上", 2, "姓陈名胖瘦李矮姨趣意思卷强壮福猪题退", "姓陈名胖李叔脸些信定"),
        ("上", 3, "辆形按盖吸管钟伙伴背颜角睡准改迟惯陪", "蓝闹钟伙背表角旁睡改掉迟"),
        ("上", 4, "化芽细根健康越粗幼摆腿乌龟嘁披短蛙", "绿化细根越粗黑条哪短孩已经"),
        ("上", 5, "展傍逛尝或者脑艺号刚附近付束鲜贴备", "傍或者球爷课号跟扫呢收准备"),
        ("上", 6, "扔错推撞谅弄破系紧突及倒理跌受刻扶", "应该错原谅校怎受扶谢"),
        ("上", 7, "赶留便赔邻居盆镜溜休息视轻脱鞋搬碰板", "赶张留便病休息轻椅板乖"),
        ("上", 8, "盘需硬贺线部涂挂求晒反伸歪乱累汗", "需纸穿然接折服求重乱容易"),
        ("上", 9, "熊鼻救法竹往升称古官墙沉装量夸神", "象鼻河法停往满像考拉船夸童"),
        ("下", 10, "垃圾引蚊环境脏厕所臭清仔招呼决惊", "扔因破护脏拾臭周未决追"),
        ("下", 11, "浪费使袋废利瓶箱超品如购尽份", "认浪费保报物情期盒付钱如"),
        ("下", 12, "设计虎各喷岸野踏旗颗印度竖拇谜奋", "亮晶狮虎各活海岸庆礼唱歌奋"),
        ("下", 13, "养虾湖狼洞沿滩丛顶必须讨论任务虽仍", "池虾森爬桥竹沿找组第忙虽"),
        ("下", 14, "滑软灰嘴胡圈喂萝卜散却咬断斤够肚躺慢", "兔眼睛圆灰饿散步尾咬肚慢"),
        ("下", 15, "偷堂吓逃痛冒抖蜜蜂假简单忍钻敢", "候堂吓冒冷汗丛谁参桌哈"),
        ("下", 16, "欺负宠俩舞吹轮数吴代替传念抬", "欺负俩吹泡结却识念低敢抬"),
        ("下", 17, "裙咖啡藏底失铁金签百消万千减算检查", "油弄倒失金试卷百等万千"),
    ],
    "P4": [
        ("上", 1, "解内预况众播续剧集精换言投掌疲倦议蹈秘密", "闻内外部众精彩拍刚建"),
        ("上", 2, "苹词丸鼓帽套递姑烟棒倾暖示忽灵挤靠撑担", "讨论串丸姑乌忽灵急怕"),
        ("上", 3, "尊敬辈警察悔脾模型碗吞舍醒眸补谎泪落批评", "尊敬偷悔架近迷补泪您"),
        ("上", 4, "值责擦扇归插阅耍劝注证皱眉默由于纷赞", "责食插注意静由于脚净任"),
        ("上", 5, "防针育继烧药澡戴项差闷胆微松勇骗闭哇并", "针束室药检查伸闭"),
        ("上", 6, "夫武族团训迎握励器丰富啦辛弃坚持段登幸亭", "功夫所团始久军辛苦健康"),
        ("上", 7, "孕妇厢乘随塑料约歉舅移命终乎滚秩序耐待悄", "厢乘劝思馆拼命挤摇抢"),
        ("上", 8, "危险遵守通规则祸另挥巨困达顺血访标义获扬", "通救另照顾司被困血"),
        ("上", 9, "盲熟民供沟洁饮摊糖歪楚依笨而", "居民铁座店味其清楚离"),
        ("下", 10, "烦螃蟹粉貌无占柜壶洒拖眯肯敲羞显", "洁粉管助无耍推喊教难"),
        ("下", 11, "曲令枪席秒冠领奖飘此既速奔摔焦亚优秀绩", "曲令举指选终既抱取"),
        ("下", 12, "鹅南北览烈旅介绍景兵列泉宾朝欣赏纪充", "顺屋商热假传围握群"),
        ("下", 13, "裂娘拜仙弹钢琴俱承拒绝之挑拆怒剩打丈柱缩", "块突婆男许宝特摸言语刻"),
        ("下", 14, "皂典筷匙拳乒兵厨蕉浸铜巧穷压罵瞪凶怜竞慌欠", "递词典挥落骂凶怜睁慌"),
        ("下", 15, "春盛秋爽舒夏炎冬寒雪堆寄邮京潮袖季世界导", "舒炎刮展观碰邮票泳希望"),
        ("下", 16, "蛇膀颈鹿壁蝴蝶趴绕丑哦释与牢钓蹲侧臂", "鸡鸭速漂趴惊奇丑挂枝晒"),
    ],
    "P5": [
        ("上", 1, "露营探袜简止独禁贵竞绑协配咽顿骨椰昏", "集迎裤鞋袜单独贵赛简轮擦顿摆感"),
        ("上", 2, "测确码填格暗距户且隔惨盯疼咳嗽诊降糊瞎", "视题连续脑持户而且松差担痛害惯"),
        ("上", 3, "材紫调盐状搅拌锅异聚犯误似恼慰惜劳", "营养蛋黄形状炒嘴异答谈似懂劳累"),
        ("上", 4, "捐效类存冻蔬饺酒村私井愁撒捧缺愉聊", "捐装鲜适糕饼私煮烧怪甜转幸福"),
        ("上", 5, "贩银资叠钞币联晨晃恐呆傻阻拦麻诚善良", "附捡联系餐撞紧飘约麻烦过阿姨诚"),
        ("上", 6, "洋孔浮肤层厚深浅死波概喘透抽载涨波激", "顶呼吸层斤深浅死湿提数脱波"),
        ("上", 7, "陆汉制造迹络未弱永曾龄眨输赢省珍", "汉制造器登未骗永溜输赢此省"),
        ("上", 8, "增添兰价免订扮仗敌攻参孝战杀胜败乡雄", "影将免领瓶代替纪孝兵乡英雄"),
        ("下", 9, "址痘嘲隐瘾控唠叨遮夹恶腰酸农惭愧恩拥", "线厌较嘲戴镜控段遮刷农珍惜"),
        ("下", 10, "初至零程基截限详胸扑衬衫扣撕肩恨狠", "招初零尽详使聪跌切扑露恨狠"),
        ("下", 11, "佳著册滨湾刺巷唯骄傲豪盼宽阔伍斗渐献缤", "棒评超熟夜刺骄傲烈舞列演整齐"),
        ("下", 12, "录构历史甲产括据统亿乙仅叹墨窄怀疑派恍悟", "骨括优艺仅官叹窄怀疑派肯"),
        ("下", 13, "遇罗顽偶诗培丙宣积倍际何混偏烫额柔凡恢", "遇耐顽鼓励积绩并洞钻温柔微"),
        ("下", 14, "栽淡扁乳浓炮否腐烂编闲挺慷慨窝幽枯", "棵巨宽阔辆升淡浓闲阴壮悄"),
        ("下", 15, "固筑震亡欧洲淹避兽击劣祖猎捕棍驾", "厚暖搭减亡防淹避神环境驾"),
    ],
    "P6": [
        ("上", 1, "克锻炼验严勤懒惰划临托艳滴埋暴狂榜", "压克梦勤复计划勇景引颜阵榜"),
        ("上", 2, "孙牵促庭谐拨智闯斜迅踩眯呀挡唇忆", "孙趣解贴共陪斜踩歪眯换挡忆"),
        ("上", 3, "蒸脆煎赠咸粥粒仿例毒财夺彼劲伟慧", "炸烤苗盘瘦汁粒除例争断伟"),
        ("上", 4, "珠链货宜质销售损修趋匆扰普趁慈祥", "价货宜量修理套趋弯腰随示趁反"),
        ("上", 5, "择述呈式创肥性贪砸碎镇锤耸糟塌捞", "达创肥垃圾铃院搬碎笨逃袋靠忍"),
        ("上", 6, "抗忠杰德江俊帅妒忌箭甘罚延罪催雾绳射妙佩", "杰俊帅议够愿罚必须盖催躲妙"),
        ("下", 7, "幅抄赚氛局厦贡置政府廊吊租吩咐津捏", "街幅抄消巧置骑底梯篮津邻拖扁厕"),
        ("下", 8, "版社章朗译妖魔鬼申悉贫余忧跨寻暂", "介绍录页码式篇义翻败鬼申牌穷算糟吞"),
        ("下", 9, "罩遭技搜索堵航幻源砖唉厉瞧虑端胀丝荡", "品按眨幻度恼厉晃敲窗尝滴存"),
        ("下", 10, "毕届恳邀致仪奏诵幕键悲稍含怨途孤", "毕邀证醒务盼踏依舍弃途坚废守"),
    ],
}

# character -> (pinyin, short English gloss). Covers every unique
# character across GRADE_LESSONS above (P2-P6). P1 keeps its own
# PINYIN_MEANING dict in seed_moe_p1.py, untouched.
PINYIN_MEANING = {
    "万": ("wàn", "ten thousand"),
    "丈": ("zhàng", "unit of length (~3.3m); husband (丈夫)"),
    "与": ("yǔ", "and"),
    "丑": ("chǒu", "ugly"),
    "专": ("zhuān", "for a particular person, occasion, purpose"),
    "且": ("qiě", "and"),
    "世": ("shì", "life"),
    "丙": ("bǐng", "third (in a numbered series)"),
    "丛": ("cóng", "cluster"),
    "丝": ("sī", "silk"),
    "丢": ("diū", "to lose"),
    "严": ("yán", "tight (closely sealed)"),
    "丰": ("fēng", "luxuriant"),
    "临": ("lín", "to face"),
    "丸": ("wán", "ball"),
    "主": ("zhǔ", "owner"),
    "丽": ("lì", "beautiful (in 美丽)"),
    "举": ("jǔ", "to lift/raise"),
    "久": ("jiǔ", "long (time)"),
    "义": ("yì", "righteousness/meaning"),
    "之": ("zhī", "(literary possessive/pronoun)"),
    "乌": ("wū", "crow; black/dark"),
    "乎": ("hū", "(classical particle)"),
    "乒": ("pīng", "bing"),
    "乖": ("guāi", "clever"),
    "乘": ("chéng", "to ride"),
    "乙": ("yǐ", "second (in a numbered series)"),
    "乡": ("xiāng", "country or countryside"),
    "乱": ("luàn", "in confusion or disorder"),
    "乳": ("rǔ", "breast"),
    "争": ("zhēng", "to strive for"),
    "于": ("yú", "at/in/to"),
    "互": ("hù", "mutual"),
    "井": ("jǐng", "water well"),
    "亚": ("yà", "second"),
    "些": ("xiē", "some/a few"),
    "亡": ("wáng", "to die"),
    "产": ("chǎn", "to give birth"),
    "京": ("jīng", "capital city"),
    "亭": ("tíng", "pavilion"),
    "亮": ("liàng", "bright"),
    "亲": ("qīn", "parent"),
    "亿": ("yì", "100 million"),
    "仅": ("jǐn", "barely"),
    "介": ("jiè", "to introduce"),
    "仍": ("réng", "still"),
    "从": ("cóng", "from"),
    "仔": ("zǎi", "meticulous"),
    "仗": ("zhàng", "weaponry"),
    "付": ("fù", "to pay"),
    "仙": ("xiān", "immortal"),
    "代": ("dài", "to substitute"),
    "令": ("lìng", "to order/command"),
    "以": ("yǐ", "with/by means of"),
    "仪": ("yí", "apparatus"),
    "价": ("jià", "price"),
    "任": ("rèn", "to appoint/duty"),
    "份": ("fèn", "measure word/portion"),
    "仿": ("fǎng", "to imitate"),
    "伍": ("wǔ", "squad of five soldiers"),
    "休": ("xiū", "to rest"),
    "众": ("zhòng", "many"),
    "优": ("yōu", "excellent"),
    "伙": ("huǒ", "partner/group (in 伙伴, companion)"),
    "伟": ("wěi", "big"),
    "传": ("chuán", "to pass on"),
    "伤": ("shāng", "to injure"),
    "伯": ("bó", "father's elder brother"),
    "伴": ("bàn", "partner"),
    "伸": ("shēn", "to stretch"),
    "似": ("shì", "to seem"),
    "但": ("dàn", "but"),
    "位": ("wèi", "position"),
    "低": ("dī", "low"),
    "住": ("zhù", "to live"),
    "何": ("hé", "what"),
    "余": ("yú", "surplus/remaining"),
    "佩": ("pèi", "to respect"),
    "佳": ("jiā", "beautiful"),
    "使": ("shǐ", "to make"),
    "例": ("lì", "example"),
    "供": ("gōng", "to provide"),
    "依": ("yī", "to depend on"),
    "侧": ("cè", "the side"),
    "便": ("biàn", "plain"),
    "促": ("cù", "urgent"),
    "俊": ("jùn", "handsome"),
    "保": ("bǎo", "to defend"),
    "俩": ("liǎ", "two (colloquial equivalent of 兩個|两个)"),
    "修": ("xiū", "to decorate"),
    "俱": ("jù", "entirely"),
    "倍": ("bèi", "times (multiplier)"),
    "倒": ("dào", "to place upside down"),
    "候": ("hòu", "to wait"),
    "借": ("jiè", "to lend"),
    "倦": ("juàn", "tired"),
    "值": ("zhí", "value"),
    "倾": ("qīng", "to overturn"),
    "假": ("jiǎ", "fake"),
    "偏": ("piān", "to lean"),
    "停": ("tíng", "to stop"),
    "健": ("jiàn", "healthy"),
    "偶": ("ǒu", "accidental"),
    "偷": ("tōu", "to steal"),
    "傍": ("bàng", "near"),
    "催": ("cuī", "to urge"),
    "傲": ("ào", "proud"),
    "傻": ("shǎ", "foolish"),
    "像": ("xiàng", "to resemble"),
    "充": ("chōng", "to fill"),
    "光": ("guāng", "light"),
    "克": ("kè", "to be able to"),
    "免": ("miǎn", "to excuse sb"),
    "全": ("quán", "all"),
    "兰": ("lán", "orchid"),
    "共": ("gòng", "common"),
    "兵": ("bīng", "soldiers"),
    "典": ("diǎn", "canon"),
    "养": ("yǎng", "to raise (animals)"),
    "兽": ("shòu", "beast"),
    "内": ("nèi", "inside"),
    "册": ("cè", "book"),
    "冒": ("mào", "to emit/risk"),
    "军": ("jūn", "army/military"),
    "农": ("nóng", "peasant"),
    "冠": ("guān", "hat"),
    "冬": ("dōng", "winter"),
    "冰": ("bīng", "ice"),
    "决": ("jué", "to decide"),
    "况": ("kuàng", "moreover"),
    "冷": ("lěng", "cold"),
    "冻": ("dòng", "to freeze"),
    "准": ("zhǔn", "to allow"),
    "减": ("jiǎn", "to lower"),
    "凡": ("fán", "ordinary"),
    "凶": ("xiōng", "terrible"),
    "击": ("jī", "to hit"),
    "分": ("fēn", "to divide"),
    "划": ("huà", "to delimit"),
    "列": ("liè", "to arrange"),
    "则": ("zé", "rule/then"),
    "刚": ("gāng", "hard"),
    "创": ("chuàng", "to begin"),
    "初": ("chū", "at first"),
    "利": ("lì", "sharp"),
    "别": ("bié", "to leave"),
    "刮": ("guā", "to scrape"),
    "制": ("zhì", "system"),
    "刺": ("cì", "thorn"),
    "刻": ("kè", "quarter (hour)"),
    "剧": ("jù", "drama/play"),
    "剩": ("shèng", "to remain"),
    "剪": ("jiǎn", "scissors"),
    "劝": ("quàn", "to advise"),
    "加": ("jiā", "to add"),
    "务": ("wù", "affair"),
    "劣": ("liè", "inferior"),
    "助": ("zhù", "to help"),
    "努": ("nǔ", "to exert"),
    "励": ("lì", "to encourage"),
    "劲": ("jìn", "strength"),
    "劳": ("láo", "to toil"),
    "勇": ("yǒng", "brave"),
    "勤": ("qín", "diligent"),
    "匆": ("cōng", "hurried"),
    "化": ("huà", "to make into"),
    "北": ("běi", "north"),
    "匙": ("shi", "spoon"),
    "区": ("qū", "area"),
    "医": ("yī", "medical"),
    "千": ("qiān", "thousand"),
    "升": ("shēng", "to ascend"),
    "协": ("xié", "to cooperate"),
    "单": ("dān", "bill"),
    "卖": ("mài", "to sell"),
    "南": ("nán", "south"),
    "卜": ("bo", "to divine"),
    "占": ("zhàn", "to take possession of"),
    "卡": ("kǎ", "to stop"),
    "卫": ("wèi", "to guard/defend"),
    "印": ("yìn", "to print"),
    "危": ("wēi", "danger"),
    "却": ("què", "but/yet"),
    "卷": ("juǎn", "to roll up"),
    "厅": ("tīng", "living room"),
    "历": ("lì", "to experience/calendar"),
    "厉": ("lì", "strict"),
    "压": ("yā", "to press"),
    "厌": ("yàn", "to loathe"),
    "厕": ("cè", "restroom"),
    "厚": ("hòu", "thick"),
    "原": ("yuán", "original/plain (land)"),
    "厢": ("xiāng", "box (in theater)"),
    "厦": ("shà", "tall building"),
    "厨": ("chú", "kitchen (in 厨房)"),
    "参": ("cān", "to take part in"),
    "叉": ("chā", "fork"),
    "及": ("jí", "and"),
    "反": ("fǎn", "contrary"),
    "取": ("qǔ", "to take"),
    "受": ("shòu", "to receive"),
    "叠": ("dié", "to fold"),
    "古": ("gǔ", "ancient"),
    "另": ("lìng", "other"),
    "叨": ("dāo", "garrulous"),
    "史": ("shǐ", "history"),
    "号": ("hào", "ordinal number"),
    "司": ("sī", "to take charge of"),
    "叹": ("tàn", "to sigh"),
    "各": ("gè", "each"),
    "吉": ("jí", "lucky"),
    "吊": ("diào", "to suspend"),
    "名": ("míng", "name"),
    "吐": ("tǔ", "to spit"),
    "向": ("xiàng", "towards"),
    "吓": ("xià", "to frighten"),
    "吞": ("tūn", "to swallow"),
    "否": ("fǒu", "to negate"),
    "吧": ("ba", "suggestion particle"),
    "吩": ("fēn", "leave instructions"),
    "含": ("hán", "to keep"),
    "吴": ("wú", "(surname)"),
    "吵": ("chǎo", "to quarrel"),
    "吸": ("xī", "to breathe"),
    "吹": ("chuī", "to blow"),
    "呀": ("ya", "exclamatory particle"),
    "呆": ("dāi", "foolish"),
    "呈": ("chéng", "to present to a superior"),
    "告": ("gào", "to say"),
    "员": ("yuán", "person"),
    "呢": ("ne", "question particle"),
    "味": ("wèi", "taste"),
    "呼": ("hū", "to call"),
    "命": ("mìng", "life"),
    "咐": ("fù", "to order"),
    "咖": ("kā", "coffee"),
    "咬": ("yǎo", "to bite"),
    "咳": ("ké", "cough"),
    "咸": ("xián", "all"),
    "咽": ("yàn", "to swallow"),
    "品": ("pǐn", "article"),
    "哇": ("wa", "exclamatory particle"),
    "响": ("xiǎng", "echo"),
    "哦": ("ó", "oh (interjection indicating doubt or surprise)"),
    "哪": ("nǎ", "how"),
    "唇": ("chún", "lip"),
    "唉": ("āi", "sigh (interjection)"),
    "唠": ("láo", "to chatter"),
    "售": ("shòu", "to sell"),
    "唯": ("wéi", "-ism"),
    "啡": ("fēi", "(in 咖啡, coffee)"),
    "啦": ("la", "exclamatory particle"),
    "喂": ("wèi", "hey"),
    "善": ("shàn", "good (virtuous)"),
    "喘": ("chuǎn", "to gasp"),
    "喷": ("pēn", "to puff"),
    "嗽": ("sòu", "cough"),
    "嘁": ("qī", "whispering sound"),
    "嘲": ("cháo", "to ridicule"),
    "嘴": ("zuǐ", "mouth"),
    "器": ("qì", "device"),
    "团": ("tuán", "round"),
    "困": ("kùn", "to trap"),
    "固": ("gù", "hard"),
    "圆": ("yuán", "circle"),
    "圈": ("quān", "circle"),
    "圾": ("jī", "(in 垃圾, garbage)"),
    "址": ("zhǐ", "location"),
    "块": ("kuài", "lump (of earth)"),
    "坚": ("jiān", "strong"),
    "坡": ("pō", "slope"),
    "垃": ("lā", "(in 垃圾, garbage)"),
    "型": ("xíng", "mold"),
    "埋": ("mái", "to bury"),
    "城": ("chéng", "city walls"),
    "培": ("péi", "to bank up with earth"),
    "基": ("jī", "base"),
    "堂": ("táng", "large room for a specific purpose"),
    "堆": ("duī", "to pile up"),
    "堵": ("dǔ", "to block up (a road, pipe etc)"),
    "塌": ("tā", "to collapse"),
    "塑": ("sù", "to model (a figure) in clay"),
    "填": ("tián", "to fill or stuff"),
    "境": ("jìng", "border"),
    "墙": ("qiáng", "wall"),
    "增": ("zēng", "to increase"),
    "墨": ("mò", "ink stick"),
    "壁": ("bì", "wall"),
    "壮": ("zhuàng", "strong/robust"),
    "壳": ("ké", "shell"),
    "壶": ("hú", "pot"),
    "处": ("chù", "place"),
    "备": ("bèi", "to prepare"),
    "复": ("fù", "to go and return"),
    "夏": ("xià", "summer"),
    "外": ("wài", "outside"),
    "夜": ("yè", "night"),
    "够": ("gòu", "enough (sufficient)"),
    "夫": ("fū", "husband"),
    "失": ("shī", "to lose"),
    "夸": ("kuā", "to boast"),
    "夹": ("jiā", "to press from either side"),
    "夺": ("duó", "to seize"),
    "奇": ("qí", "strange"),
    "奋": ("fèn", "to exert oneself"),
    "奏": ("zòu", "to play music"),
    "奔": ("bēn", "to hurry"),
    "奖": ("jiǎng", "prize"),
    "套": ("tào", "to cover"),
    "如": ("rú", "as"),
    "妇": ("fù", "woman"),
    "妒": ("dù", "to envy (success, talent)"),
    "妖": ("yāo", "goblin"),
    "妙": ("miào", "clever"),
    "始": ("shǐ", "to begin"),
    "姑": ("gū", "paternal aunt"),
    "姓": ("xìng", "family name"),
    "姨": ("yí", "mother's sister"),
    "娃": ("wá", "baby"),
    "娘": ("niáng", "mother"),
    "婆": ("pó", "grandmother"),
    "孔": ("kǒng", "hole"),
    "孕": ("yùn", "pregnant"),
    "存": ("cún", "to exist"),
    "孙": ("sūn", "grandson"),
    "孝": ("xiào", "filial piety or obedience"),
    "季": ("jì", "season"),
    "孤": ("gū", "lone"),
    "守": ("shǒu", "to guard"),
    "官": ("guān", "government official"),
    "定": ("dìng", "to set"),
    "宜": ("yí", "proper"),
    "宝": ("bǎo", "jewel"),
    "实": ("shí", "real"),
    "宠": ("chǒng", "to love"),
    "客": ("kè", "customer"),
    "宣": ("xuān", "to declare (publicly)"),
    "室": ("shì", "room"),
    "害": ("hài", "to do harm to"),
    "容": ("róng", "to hold"),
    "宽": ("kuān", "lenient"),
    "宾": ("bīn", "visitor"),
    "寄": ("jì", "to send"),
    "密": ("mì", "secret"),
    "富": ("fù", "rich"),
    "寒": ("hán", "cold"),
    "察": ("chá", "to examine/observe"),
    "寻": ("xún", "to search"),
    "导": ("dǎo", "to transmit"),
    "射": ("shè", "to shoot"),
    "将": ("jiāng", "will"),
    "尊": ("zūn", "senior"),
    "尝": ("cháng", "to taste"),
    "就": ("jiù", "at once"),
    "尽": ("jǐn", "to the greatest extent"),
    "局": ("jú", "narrow"),
    "层": ("céng", "layer"),
    "居": ("jū", "to reside"),
    "届": ("jiè", "to arrive at (place or time)"),
    "展": ("zhǎn", "to spread out"),
    "岁": ("suì", "years old"),
    "岛": ("dǎo", "island"),
    "岸": ("àn", "bank"),
    "巧": ("qiǎo", "opportunely"),
    "巨": ("jù", "very large"),
    "差": ("chà", "to differ from"),
    "已": ("yǐ", "already"),
    "巷": ("xiàng", "lane"),
    "币": ("bì", "money"),
    "市": ("shì", "market"),
    "布": ("bù", "to announce"),
    "帅": ("shuài", "handsome"),
    "希": ("xī", "to hope"),
    "席": ("xí", "woven mat"),
    "帮": ("bāng", "to help"),
    "帽": ("mào", "hat/cap"),
    "幅": ("fú", "width"),
    "幕": ("mù", "curtain or screen"),
    "平": ("píng", "flat"),
    "年": ("nián", "year"),
    "并": ("bìng", "and"),
    "幸": ("xìng", "trusted"),
    "幻": ("huàn", "fantasy"),
    "幼": ("yòu", "young"),
    "幽": ("yōu", "remote"),
    "序": ("xù", "order"),
    "应": ("yīng", "to agree (to do sth)"),
    "底": ("dǐ", "background"),
    "府": ("fǔ", "seat of government"),
    "废": ("fèi", "to abolish"),
    "度": ("dù", "to pass"),
    "座": ("zuò", "seat"),
    "庭": ("tíng", "main hall"),
    "康": ("kāng", "healthy"),
    "廊": ("láng", "corridor"),
    "延": ("yán", "to prolong"),
    "建": ("jiàn", "to establish"),
    "异": ("yì", "different"),
    "弃": ("qì", "to abandon"),
    "弄": ("nòng", "to do"),
    "式": ("shì", "type"),
    "引": ("yǐn", "to draw (e.g. a bow)"),
    "张": ("zhāng", "to open up"),
    "弱": ("ruò", "weak"),
    "弹": ("dàn", "crossball"),
    "强": ("qiáng", "strong"),
    "归": ("guī", "to return"),
    "当": ("dāng", "ding dong (bell)"),
    "录": ("lù", "diary"),
    "形": ("xíng", "to appear"),
    "彩": ("cǎi", "variety"),
    "影": ("yǐng", "picture"),
    "彼": ("bǐ", "that"),
    "往": ("wǎng", "to go (in a direction)"),
    "待": ("dài", "to wait"),
    "得": ("dé", "to obtain"),
    "微": ("wēi", "tiny/slight"),
    "德": ("dé", "virtue"),
    "必": ("bì", "certainly"),
    "忆": ("yì", "to recollect"),
    "忌": ("jì", "to be jealous of"),
    "忍": ("rěn", "to bear"),
    "忘": ("wàng", "to forget"),
    "忙": ("máng", "busy"),
    "忠": ("zhōng", "loyal"),
    "忧": ("yōu", "to worry"),
    "念": ("niàn", "to read"),
    "忽": ("hū", "to neglect"),
    "怀": ("huái", "bosom"),
    "怒": ("nù", "anger"),
    "怕": ("pà", "to be afraid"),
    "怜": ("lián", "to pity"),
    "思": ("sī", "to think"),
    "急": ("jí", "urgent"),
    "性": ("xìng", "nature"),
    "怨": ("yuàn", "to blame"),
    "怪": ("guài", "bewildering"),
    "总": ("zǒng", "always"),
    "恍": ("huǎng", "disappointed"),
    "恐": ("kǒng", "afraid"),
    "恢": ("huī", "to restore"),
    "恨": ("hèn", "to hate"),
    "恩": ("ēn", "favor"),
    "息": ("xī", "breath"),
    "恳": ("kěn", "earnest"),
    "恶": ("è", "evil"),
    "恼": ("nǎo", "to get angry"),
    "悄": ("qiāo", "quiet"),
    "悉": ("xī", "in all cases"),
    "悔": ("huǐ", "to regret"),
    "悟": ("wù", "to comprehend"),
    "您": ("nín", "you (polite)"),
    "悲": ("bēi", "sad"),
    "情": ("qíng", "feeling"),
    "惊": ("jīng", "to startle"),
    "惜": ("xī", "to cherish"),
    "惨": ("cǎn", "miserable"),
    "惭": ("cán", "ashamed"),
    "惯": ("guàn", "accustomed to"),
    "惰": ("duò", "lazy"),
    "想": ("xiǎng", "to think"),
    "愁": ("chóu", "to worry about"),
    "愉": ("yú", "pleased"),
    "意": ("yì", "idea"),
    "愧": ("kuì", "ashamed"),
    "愿": ("yuàn", "honest"),
    "慈": ("cí", "compassionate"),
    "慌": ("huāng", "to get panicky"),
    "慢": ("màn", "slow"),
    "慧": ("huì", "intelligent"),
    "慨": ("kǎi", "to sigh (with emotion)"),
    "慰": ("wèi", "to comfort"),
    "慷": ("kāng", "generous"),
    "懂": ("dǒng", "to understand"),
    "懒": ("lǎn", "lazy"),
    "成": ("chéng", "to succeed"),
    "或": ("huò", "maybe"),
    "战": ("zhàn", "to fight"),
    "截": ("jié", "to cut off (a length)"),
    "戴": ("dài", "to put on or wear (glasses, hat, gloves etc)"),
    "户": ("hù", "a household"),
    "所": ("suǒ", "actually"),
    "扁": ("biǎn", "flat"),
    "扇": ("shàn", "fan"),
    "才": ("cái", "ability"),
    "扑": ("pū", "to throw oneself at"),
    "打": ("dǎ", "to beat"),
    "扔": ("rēng", "to throw"),
    "托": ("tuō", "prop"),
    "扣": ("kòu", "to fasten"),
    "扬": ("yáng", "to raise"),
    "扮": ("bàn", "to disguise oneself as"),
    "扰": ("rǎo", "to disturb"),
    "扶": ("fú", "to support with the hand"),
    "批": ("pī", "to ascertain"),
    "找": ("zhǎo", "to try to find"),
    "承": ("chéng", "to bear/undertake"),
    "技": ("jì", "skill"),
    "抄": ("chāo", "to make a copy"),
    "抓": ("zhuā", "to grab"),
    "投": ("tóu", "to cast"),
    "抖": ("dǒu", "to tremble"),
    "抗": ("kàng", "to resist"),
    "折": ("zhé", "to break"),
    "抢": ("qiǎng", "to fight over"),
    "护": ("hù", "to protect"),
    "披": ("pī", "to drape over one's shoulders"),
    "抬": ("tái", "to lift"),
    "抽": ("chōu", "to draw out"),
    "担": ("dān", "to undertake"),
    "拆": ("chāi", "to tear open"),
    "拇": ("mǔ", "thumb"),
    "拉": ("lā", "to pull"),
    "拌": ("bàn", "to mix"),
    "拒": ("jù", "to resist"),
    "拔": ("bá", "to pull up"),
    "拖": ("tuō", "to drag"),
    "招": ("zhāo", "to recruit"),
    "拜": ("bài", "to pay respect"),
    "拥": ("yōng", "to hold"),
    "拦": ("lán", "to block sb's path"),
    "拨": ("bō", "to move with hand/dial"),
    "择": ("zé", "to select"),
    "括": ("kuò", "to enclose"),
    "拳": ("quán", "fist"),
    "拼": ("pīn", "to piece together"),
    "持": ("chí", "to hold"),
    "挂": ("guà", "to hang or suspend (from a hook etc)"),
    "指": ("zhǐ", "finger"),
    "按": ("àn", "to press"),
    "挑": ("tiāo", "to carry on a shoulder pole"),
    "挖": ("wā", "to dig"),
    "挡": ("dǎng", "to resist"),
    "挤": ("jǐ", "to crowd in"),
    "挥": ("huī", "to wave"),
    "挺": ("tǐng", "straight"),
    "捉": ("zhuō", "to clutch"),
    "捏": ("niē", "to pinch (with one's fingers)"),
    "捐": ("juān", "to contribute"),
    "捕": ("bǔ", "to catch"),
    "捞": ("lāo", "to fish up"),
    "损": ("sǔn", "to decrease"),
    "捡": ("jiǎn", "to pick up"),
    "换": ("huàn", "to exchange"),
    "捧": ("pěng", "to clasp"),
    "据": ("jù", "according to"),
    "掉": ("diào", "to fall"),
    "掌": ("zhǎng", "palm of the hand"),
    "排": ("pái", "a row"),
    "探": ("tàn", "to explore"),
    "接": ("jiē", "to receive"),
    "控": ("kòng", "to control"),
    "推": ("tuī", "to push"),
    "插": ("chā", "to insert"),
    "握": ("wò", "to hold"),
    "搅": ("jiǎo", "to disturb"),
    "搜": ("sōu", "to search"),
    "搬": ("bān", "to move (i.e. relocate oneself)"),
    "搭": ("dā", "to put up"),
    "摆": ("bǎi", "to arrange"),
    "摇": ("yáo", "to shake"),
    "摊": ("tān", "to spread out"),
    "摔": ("shuāi", "to throw down"),
    "摘": ("zhāi", "to take"),
    "摸": ("mō", "to feel with the hand"),
    "撑": ("chēng", "to support"),
    "撒": ("sā", "to let go"),
    "撕": ("sī", "to tear"),
    "撞": ("zhuàng", "to knock against"),
    "播": ("bō", "to sow"),
    "操": ("cāo", "to exercise/operate"),
    "擦": ("cā", "to wipe"),
    "改": ("gǎi", "to change"),
    "攻": ("gōng", "to attack"),
    "政": ("zhèng", "political"),
    "效": ("xiào", "to imitate"),
    "敌": ("dí", "enemy"),
    "救": ("jiù", "to save"),
    "教": ("jiào", "religion"),
    "敢": ("gǎn", "to dare"),
    "散": ("sàn", "to scatter"),
    "敬": ("jìng", "to respect"),
    "数": ("shù", "number"),
    "敲": ("qiāo", "to hit"),
    "整": ("zhěng", "exactly"),
    "斗": ("dòu", "to fight/contend"),
    "料": ("liào", "material"),
    "斜": ("xié", "inclined"),
    "斤": ("jīn", "catty"),
    "断": ("duàn", "to break"),
    "新": ("xīn", "new"),
    "旁": ("páng", "one side"),
    "旅": ("lǚ", "trip"),
    "族": ("zú", "race"),
    "旗": ("qí", "flag"),
    "无": ("wú", "not to have"),
    "既": ("jì", "already"),
    "时": ("shí", "time/hour"),
    "昏": ("hūn", "muddle-headed"),
    "易": ("yì", "easy"),
    "春": ("chūn", "spring (season)"),
    "显": ("xiǎn", "to make visible"),
    "晃": ("huǎng", "to dazzle"),
    "晒": ("shài", "to bask in (the sunshine)"),
    "晨": ("chén", "morning"),
    "普": ("pǔ", "general"),
    "景": ("jǐng", "bright"),
    "晴": ("qíng", "clear"),
    "晶": ("jīng", "crystal"),
    "智": ("zhì", "wisdom"),
    "暂": ("zàn", "temporary"),
    "暖": ("nuǎn", "warm"),
    "暗": ("àn", "dark"),
    "暴": ("bào", "sudden"),
    "曲": ("qū", "bent"),
    "更": ("gèng", "more"),
    "曾": ("céng", "once"),
    "替": ("tì", "to substitute for"),
    "朗": ("lǎng", "clear"),
    "望": ("wàng", "full moon"),
    "朝": ("cháo", "imperial or royal court"),
    "未": ("wèi", "not yet"),
    "术": ("shù", "method"),
    "机": ("jī", "machine"),
    "杀": ("shā", "to kill"),
    "李": ("lǐ", "plum"),
    "材": ("cái", "material"),
    "村": ("cūn", "village"),
    "束": ("shù", "to bind"),
    "杯": ("bēi", "cup"),
    "杰": ("jié", "hero"),
    "松": ("sōng", "pine"),
    "板": ("bǎn", "board"),
    "极": ("jí", "extremely"),
    "构": ("gòu", "to reach by stretching"),
    "林": ("lín", "forest/woods"),
    "枝": ("zhī", "branch"),
    "枪": ("qiāng", "gun"),
    "枯": ("kū", "dried up"),
    "架": ("jià", "to support"),
    "柔": ("róu", "soft"),
    "柜": ("guì", "cupboard"),
    "查": ("chá", "to research"),
    "柱": ("zhù", "pillar"),
    "标": ("biāo", "mark"),
    "树": ("shù", "tree"),
    "样": ("yàng", "manner"),
    "根": ("gēn", "root"),
    "格": ("gé", "square"),
    "栽": ("zāi", "to grow"),
    "案": ("àn", "incident"),
    "桥": ("qiáo", "bridge"),
    "桶": ("tǒng", "bucket"),
    "梁": ("liáng", "beam/bridge"),
    "梦": ("mèng", "dream"),
    "检": ("jiǎn", "to check"),
    "棋": ("qí", "chess"),
    "棍": ("gùn", "stick"),
    "棒": ("bàng", "stick"),
    "森": ("sēn", "forest (dense trees)"),
    "棵": ("kē", "measure word for plants"),
    "植": ("zhí", "to plant"),
    "椰": ("yē", "coconut palm"),
    "楚": ("chǔ", "clear/neat (in 清楚)"),
    "楼": ("lóu", "house with more than 1 story"),
    "概": ("gài", "general"),
    "榜": ("bǎng", "notice or announcement"),
    "模": ("mó", "to imitate"),
    "欠": ("qiàn", "deficient"),
    "次": ("cì", "next in sequence"),
    "欣": ("xīn", "happy"),
    "欧": ("ōu", "Europe"),
    "欺": ("qī", "to take unfair advantage of"),
    "歉": ("qiàn", "to apologize"),
    "止": ("zhǐ", "to stop"),
    "此": ("cǐ", "this"),
    "武": ("wǔ", "martial"),
    "歪": ("wāi", "askew"),
    "死": ("sǐ", "to die"),
    "段": ("duàn", "paragraph"),
    "毒": ("dú", "poison"),
    "比": ("bǐ", "to compare"),
    "毕": ("bì", "the whole of"),
    "民": ("mín", "the people"),
    "氛": ("fēn", "miasma"),
    "永": ("yǒng", "forever"),
    "求": ("qiú", "to seek"),
    "汉": ("hàn", "man"),
    "汗": ("hàn", "perspiration"),
    "江": ("jiāng", "river"),
    "池": ("chí", "pond"),
    "汽": ("qì", "steam"),
    "沉": ("chén", "to submerge"),
    "沙": ("shā", "granule"),
    "沟": ("gōu", "ditch"),
    "油": ("yóu", "oil"),
    "沿": ("yán", "along"),
    "泉": ("quán", "spring (small stream)"),
    "法": ("fǎ", "law"),
    "波": ("bō", "wave"),
    "泥": ("ní", "mud"),
    "注": ("zhù", "to inject"),
    "泪": ("lèi", "tears"),
    "泳": ("yǒng", "swimming"),
    "洁": ("jié", "clean"),
    "洋": ("yáng", "ocean"),
    "洒": ("sǎ", "to sprinkle"),
    "洞": ("dòng", "cave"),
    "津": ("jīn", "saliva"),
    "洲": ("zhōu", "continent"),
    "活": ("huó", "to live"),
    "派": ("pài", "clique"),
    "浅": ("qiǎn", "shallow"),
    "浇": ("jiāo", "to pour liquid"),
    "测": ("cè", "to survey"),
    "浓": ("nóng", "concentrated"),
    "浪": ("làng", "wave"),
    "浮": ("fú", "to float"),
    "海": ("hǎi", "ocean"),
    "浸": ("jìn", "to immerse"),
    "涂": ("tú", "to apply (paint etc)"),
    "消": ("xiāo", "to disappear"),
    "涨": ("zhǎng", "to rise (of prices, rivers)"),
    "淋": ("lín", "to sprinkle"),
    "淡": ("dàn", "insipid"),
    "深": ("shēn", "deep"),
    "混": ("hùn", "to mix"),
    "淹": ("yān", "to flood"),
    "添": ("tiān", "to add"),
    "清": ("qīng", "clear"),
    "渐": ("jiàn", "gradual"),
    "温": ("wēn", "warm"),
    "渴": ("kě", "thirsty"),
    "湖": ("hú", "lake"),
    "湾": ("wān", "bay"),
    "湿": ("shī", "moist"),
    "源": ("yuán", "root"),
    "溜": ("liū", "to slip away"),
    "滑": ("huá", "to slip"),
    "滚": ("gǔn", "to boil"),
    "满": ("mǎn", "to fill"),
    "滨": ("bīn", "shore"),
    "滩": ("tān", "beach"),
    "滴": ("dī", "a drop"),
    "漂": ("piāo", "to float"),
    "演": ("yǎn", "to develop"),
    "潮": ("cháo", "tide"),
    "澡": ("zǎo", "bath"),
    "激": ("jī", "to arouse"),
    "灭": ("miè", "to extinguish or put out"),
    "灯": ("dēng", "lamp"),
    "灰": ("huī", "ash"),
    "灵": ("líng", "quick"),
    "灾": ("zāi", "disaster"),
    "炎": ("yán", "flame"),
    "炒": ("chǎo", "to sauté"),
    "炮": ("pào", "cannon"),
    "炸": ("zhà", "to explode"),
    "炼": ("liàn", "to refine"),
    "烂": ("làn", "soft"),
    "烈": ("liè", "ardent"),
    "烟": ("yān", "cigarette or pipe tobacco"),
    "烤": ("kǎo", "to roast"),
    "烦": ("fán", "to feel vexed"),
    "烧": ("shāo", "to burn"),
    "烫": ("tàng", "to scald"),
    "热": ("rè", "to warm up"),
    "焦": ("jiāo", "burnt"),
    "然": ("rán", "correct"),
    "煎": ("jiān", "to pan fry"),
    "照": ("zhào", "to shine"),
    "煮": ("zhǔ", "to cook"),
    "熊": ("xióng", "bear"),
    "熟": ("shú", "cooked (of food)"),
    "爬": ("pá", "to crawl"),
    "爽": ("shuǎng", "bright"),
    "版": ("bǎn", "a register"),
    "牢": ("láo", "firm"),
    "牵": ("qiān", "to lead along"),
    "特": ("tè", "special"),
    "犯": ("fàn", "to violate"),
    "状": ("zhuàng", "accusation"),
    "狂": ("kuáng", "mad"),
    "狠": ("hěn", "ruthless"),
    "独": ("dú", "alone"),
    "狼": ("láng", "wolf"),
    "猎": ("liè", "hunting"),
    "猜": ("cāi", "to guess"),
    "猪": ("zhū", "hog"),
    "献": ("xiàn", "to offer"),
    "玉": ("yù", "jade"),
    "环": ("huán", "ring"),
    "现": ("xiàn", "to appear"),
    "珍": ("zhēn", "precious thing"),
    "珠": ("zhū", "bead"),
    "班": ("bān", "team"),
    "理": ("lǐ", "texture"),
    "琴": ("qín", "guqin 古琴[gu3 qin2] (a type of zither)"),
    "瓶": ("píng", "bottle"),
    "甘": ("gān", "sweet"),
    "由": ("yóu", "to follow"),
    "甲": ("jiǎ", "first (in a numbered series)/armor"),
    "申": ("shēn", "to state/apply"),
    "界": ("jiè", "boundary"),
    "留": ("liú", "to stay/leave behind"),
    "番": ("fān", "foreign (non-Chinese)"),
    "疑": ("yí", "to doubt"),
    "疲": ("pí", "weary"),
    "疼": ("téng", "sore"),
    "病": ("bìng", "illness"),
    "痘": ("dòu", "pimple"),
    "痛": ("tòng", "ache"),
    "瘦": ("shòu", "thin"),
    "瘾": ("yǐn", "addiction"),
    "登": ("dēng", "to scale (a height)"),
    "百": ("bǎi", "hundred"),
    "皂": ("zào", "soap"),
    "皱": ("zhòu", "to wrinkle"),
    "盆": ("pén", "basin"),
    "盐": ("yán", "salt"),
    "盒": ("hé", "small box"),
    "盖": ("gài", "lid"),
    "盘": ("pán", "plate"),
    "盛": ("shèng", "flourishing"),
    "盯": ("dīng", "to watch attentively"),
    "盲": ("máng", "blind"),
    "相": ("xiāng", "each other"),
    "盼": ("pàn", "to hope for"),
    "省": ("shěng", "to save"),
    "眉": ("méi", "eyebrow"),
    "真": ("zhēn", "really"),
    "眨": ("zhǎ", "to blink"),
    "眯": ("mī", "to narrow one's eyes"),
    "眸": ("móu", "pupil (of the eye)"),
    "着": ("zhe", "aspect particle indicating action in progress"),
    "睡": ("shuì", "to sleep"),
    "瞎": ("xiā", "blind"),
    "瞧": ("qiáo", "to look at"),
    "瞪": ("dèng", "to open (one's eyes) wide"),
    "知": ("zhī", "to know"),
    "短": ("duǎn", "short"),
    "矮": ("ǎi", "low"),
    "码": ("mǎ", "weight"),
    "砖": ("zhuān", "brick"),
    "破": ("pò", "broken"),
    "砸": ("zá", "to smash"),
    "硬": ("yìng", "hard"),
    "确": ("què", "authenticated"),
    "碎": ("suì", "to break down"),
    "碗": ("wǎn", "bowl"),
    "碰": ("pèng", "to touch"),
    "示": ("shì", "to show"),
    "礼": ("lǐ", "gift"),
    "社": ("shè", "society"),
    "祖": ("zǔ", "ancestor"),
    "神": ("shén", "deity"),
    "祥": ("xiáng", "auspicious"),
    "票": ("piào", "ticket"),
    "祸": ("huò", "disaster/misfortune"),
    "禁": ("jìn", "to prohibit"),
    "福": ("fú", "good fortune"),
    "离": ("lí", "to leave"),
    "秀": ("xiù", "handsome"),
    "私": ("sī", "personal"),
    "秋": ("qiū", "autumn"),
    "种": ("zhǒng", "seed"),
    "科": ("kē", "branch of study"),
    "秒": ("miǎo", "second (unit of time)"),
    "秘": ("mì", "secret"),
    "租": ("zū", "to hire"),
    "秩": ("zhì", "order"),
    "积": ("jī", "to amass"),
    "称": ("chēng", "to weigh"),
    "移": ("yí", "to move"),
    "程": ("chéng", "rule"),
    "稍": ("shāo", "somewhat"),
    "穷": ("qióng", "poor"),
    "空": ("kōng", "empty"),
    "突": ("tū", "to dash"),
    "窄": ("zhǎi", "narrow"),
    "窗": ("chuāng", "window"),
    "窝": ("wō", "nest"),
    "竖": ("shù", "to erect"),
    "竞": ("jìng", "to compete"),
    "章": ("zhāng", "chapter"),
    "端": ("duān", "end"),
    "竹": ("zhú", "bamboo"),
    "笨": ("bèn", "stupid"),
    "第": ("dì", "ordinal prefix (e.g. 第一, first)"),
    "等": ("děng", "class"),
    "筑": ("zhù", "to build"),
    "答": ("dá", "reply"),
    "筷": ("kuài", "chopstick"),
    "签": ("qiān", "to sign one's name"),
    "简": ("jiǎn", "simple"),
    "算": ("suàn", "to regard as"),
    "管": ("guǎn", "to take care (of)"),
    "箭": ("jiàn", "arrow"),
    "箱": ("xiāng", "box"),
    "篇": ("piān", "sheet"),
    "类": ("lèi", "kind"),
    "粉": ("fěn", "powder"),
    "粒": ("lì", "grain"),
    "粗": ("cū", "coarse"),
    "粥": ("zhōu", "congee"),
    "精": ("jīng", "essence"),
    "糊": ("hú", "muddled"),
    "糕": ("gāo", "cake"),
    "糖": ("táng", "sugar"),
    "糟": ("zāo", "dregs"),
    "系": ("xì", "to connect"),
    "索": ("suǒ", "to search"),
    "紧": ("jǐn", "tight"),
    "紫": ("zǐ", "purple"),
    "累": ("lèi", "tired"),
    "约": ("yuē", "to make an appointment"),
    "级": ("jí", "level"),
    "纪": ("jì", "record/era"),
    "纷": ("fēn", "numerous"),
    "纸": ("zhǐ", "paper"),
    "线": ("xiàn", "thread"),
    "练": ("liàn", "to practice"),
    "细": ("xì", "thin or slender"),
    "终": ("zhōng", "end"),
    "绍": ("shào", "to continue"),
    "经": ("jīng", "classics"),
    "绑": ("bǎng", "to tie"),
    "结": ("jié", "to tie/knot; to bear (fruit)"),
    "绕": ("rào", "to wind"),
    "绘": ("huì", "to draw"),
    "络": ("luò", "net-like object"),
    "绝": ("jué", "to cut short"),
    "统": ("tǒng", "to gather"),
    "继": ("jì", "to continue"),
    "绩": ("jì", "to spin (hemp etc)"),
    "续": ("xù", "to continue"),
    "绳": ("shéng", "rope"),
    "绿": ("lǜ", "green"),
    "编": ("biān", "to weave"),
    "缤": ("bīn", "helter-skelter"),
    "缩": ("suō", "to withdraw"),
    "缺": ("quē", "deficiency"),
    "罗": ("luó", "gauze"),
    "罚": ("fá", "to punish"),
    "罩": ("zhào", "cover"),
    "罪": ("zuì", "guilt"),
    "置": ("zhì", "to install"),
    "罵": ("mà", "to scold"),
    "美": ("měi", "beautiful"),
    "羞": ("xiū", "shy"),
    "群": ("qún", "group"),
    "羽": ("yǔ", "feather"),
    "翅": ("chì", "wing"),
    "翻": ("fān", "to turn over"),
    "考": ("kǎo", "to beat"),
    "者": ("zhě", "-er"),
    "而": ("ér", "and"),
    "耍": ("shuǎ", "to play with"),
    "耐": ("nài", "capable of enduring"),
    "耸": ("sǒng", "to excite"),
    "聊": ("liáo", "to chat"),
    "联": ("lián", "to ally"),
    "聚": ("jù", "to congregate"),
    "聪": ("cōng", "quick at hearing"),
    "肚": ("dù", "belly"),
    "肠": ("cháng", "intestines"),
    "肤": ("fū", "skin"),
    "肥": ("féi", "fat"),
    "肩": ("jiān", "shoulder"),
    "肯": ("kěn", "willing to"),
    "育": ("yù", "to have children"),
    "胀": ("zhàng", "dropsical"),
    "胆": ("dǎn", "gall bladder"),
    "背": ("bèi", "the back of a body or object"),
    "胖": ("pàng", "fat"),
    "胜": ("shèng", "victory"),
    "胡": ("hú", "(in 胡子, beard; carelessly)"),
    "胸": ("xiōng", "chest"),
    "能": ("néng", "can"),
    "脆": ("cuì", "crisp"),
    "脏": ("zàng", "viscera"),
    "脑": ("nǎo", "brain"),
    "脚": ("jiǎo", "foot"),
    "脱": ("tuō", "to shed"),
    "脾": ("pí", "spleen"),
    "腐": ("fǔ", "decay"),
    "腰": ("yāo", "waist"),
    "腿": ("tuǐ", "leg"),
    "膀": ("bǎng", "upper arm"),
    "臂": ("bì", "arm"),
    "臭": ("chòu", "stench"),
    "至": ("zhì", "to arrive"),
    "致": ("zhì", "to cause/send; fine and detailed"),
    "舅": ("jiù", "maternal uncle"),
    "舍": ("shě", "to give up"),
    "舒": ("shū", "to stretch"),
    "舞": ("wǔ", "to dance"),
    "航": ("háng", "boat"),
    "船": ("chuán", "boat"),
    "良": ("liáng", "good"),
    "艳": ("yàn", "colorful"),
    "艺": ("yì", "skill"),
    "芽": ("yá", "bud"),
    "英": ("yīng", "hero/petal (in 英雄, hero)"),
    "苹": ("píng", "duckweed"),
    "茄": ("qié", "eggplant (in 茄子)"),
    "茶": ("chá", "tea"),
    "荡": ("dàng", "to wash"),
    "药": ("yào", "leaf of the iris"),
    "获": ("huò", "to catch"),
    "萝": ("luó", "radish"),
    "营": ("yíng", "camp"),
    "落": ("luò", "to fall or drop"),
    "著": ("zhù", "to make known"),
    "蒸": ("zhēng", "to evaporate"),
    "蓝": ("lán", "blue"),
    "蔬": ("shū", "vegetables"),
    "蕉": ("jiāo", "banana"),
    "藏": ("cáng", "to conceal"),
    "虎": ("hǔ", "tiger"),
    "虑": ("lǜ", "to think over"),
    "虹": ("hóng", "rainbow"),
    "虽": ("suī", "although"),
    "虾": ("xiā", "shrimp"),
    "蚁": ("yǐ", "ant"),
    "蚂": ("mǎ", "ant"),
    "蚊": ("wén", "mosquito"),
    "蛇": ("shé", "snake"),
    "蛙": ("wā", "frog"),
    "蜂": ("fēng", "bee"),
    "蜜": ("mì", "honey"),
    "蝴": ("hú", "butterfly"),
    "蝶": ("dié", "butterfly"),
    "螃": ("páng", "crab"),
    "蟹": ("xiè", "crab"),
    "血": ("xuè", "blood"),
    "行": ("xíng", "to walk"),
    "街": ("jiē", "street"),
    "补": ("bǔ", "to repair"),
    "表": ("biǎo", "exterior surface"),
    "衫": ("shān", "garment"),
    "衬": ("chèn", "to line"),
    "袋": ("dài", "pouch"),
    "袖": ("xiù", "sleeve"),
    "袜": ("wà", "socks"),
    "裂": ("liè", "to split"),
    "装": ("zhuāng", "adornment"),
    "裙": ("qún", "skirt"),
    "观": ("guān", "to look at"),
    "规": ("guī", "compass"),
    "视": ("shì", "to look at"),
    "览": ("lǎn", "to look at"),
    "觉": ("jué", "to feel"),
    "角": ("jiǎo", "angle"),
    "解": ("jiě", "to divide"),
    "言": ("yán", "words"),
    "警": ("jǐng", "to alert"),
    "计": ("jì", "to calculate"),
    "订": ("dìng", "to agree"),
    "讨": ("tǎo", "to invite"),
    "让": ("ràng", "to yield"),
    "训": ("xùn", "to teach"),
    "议": ("yì", "to comment on"),
    "记": ("jì", "to record"),
    "许": ("xǔ", "to allow"),
    "论": ("lùn", "opinion"),
    "设": ("shè", "to set up"),
    "访": ("fǎng", "to visit"),
    "证": ("zhèng", "to admonish"),
    "评": ("píng", "to discuss"),
    "识": ("shí", "to know"),
    "诉": ("sù", "to complain"),
    "诊": ("zhěn", "to examine or treat medically"),
    "词": ("cí", "word/term"),
    "译": ("yì", "to translate"),
    "试": ("shì", "to test"),
    "诗": ("shī", "poem"),
    "诚": ("chéng", "sincere"),
    "该": ("gāi", "should"),
    "详": ("xiáng", "detailed"),
    "误": ("wù", "mistake"),
    "诵": ("sòng", "to read aloud"),
    "读": ("dú", "to read"),
    "调": ("diào", "to transfer"),
    "谅": ("liàng", "to show understanding"),
    "谎": ("huǎng", "lies"),
    "谐": ("xié", "harmonious"),
    "谜": ("mí", "riddle"),
    "豪": ("háo", "grand"),
    "貌": ("mào", "appearance"),
    "负": ("fù", "to bear"),
    "贡": ("gòng", "to offer tribute"),
    "财": ("cái", "money"),
    "责": ("zé", "duty"),
    "败": ("bài", "to defeat"),
    "货": ("huò", "goods"),
    "质": ("zhì", "character"),
    "贩": ("fàn", "to deal in"),
    "贪": ("tān", "to have a voracious desire for"),
    "贫": ("pín", "poor"),
    "购": ("gòu", "to buy"),
    "贴": ("tiē", "to stick"),
    "贵": ("guì", "expensive"),
    "费": ("fèi", "to cost"),
    "贺": ("hè", "to congratulate"),
    "资": ("zī", "resources"),
    "赏": ("shǎng", "to bestow (a reward)"),
    "赔": ("péi", "to compensate for loss"),
    "赚": ("zhuàn", "to earn"),
    "赞": ("zàn", "to praise"),
    "赠": ("zèng", "to give as a present"),
    "赢": ("yíng", "to beat"),
    "赶": ("gǎn", "to overtake"),
    "趁": ("chèn", "to avail oneself of"),
    "超": ("chāo", "to exceed"),
    "越": ("yuè", "to exceed/surpass"),
    "趋": ("qū", "to hasten"),
    "趣": ("qù", "interesting"),
    "趴": ("pā", "to lie on one's stomach"),
    "跌": ("diē", "to fall"),
    "距": ("jù", "at a distance of"),
    "跟": ("gēn", "heel"),
    "跨": ("kuà", "to step across"),
    "路": ("lù", "road"),
    "跳": ("tiào", "to jump"),
    "踏": ("tà", "to tread"),
    "踢": ("tī", "to kick"),
    "踩": ("cǎi", "to step on"),
    "蹈": ("dǎo", "to tread on"),
    "蹲": ("dūn", "to crouch"),
    "躺": ("tǎng", "to recline"),
    "转": ("zhuǎn", "to turn"),
    "轮": ("lún", "wheel"),
    "软": ("ruǎn", "soft"),
    "轻": ("qīng", "light"),
    "载": ("zài", "to carry"),
    "辆": ("liàng", "measure word for vehicles"),
    "辈": ("bèi", "lifetime"),
    "输": ("shū", "to lose"),
    "辛": ("xīn", "hard"),
    "达": ("dá", "to attain"),
    "迅": ("xùn", "rapid"),
    "过": ("guò", "to cross"),
    "迎": ("yíng", "to welcome"),
    "运": ("yùn", "to move"),
    "近": ("jìn", "near"),
    "远": ("yuǎn", "far"),
    "迟": ("chí", "late"),
    "述": ("shù", "to state"),
    "迷": ("mí", "to bewilder"),
    "迹": ("jì", "footprint"),
    "追": ("zhuī", "to chase after"),
    "退": ("tuì", "to retreat"),
    "送": ("sòng", "to deliver"),
    "逃": ("táo", "to escape"),
    "透": ("tòu", "to penetrate"),
    "递": ("dì", "to hand over"),
    "途": ("tú", "way"),
    "通": ("tōng", "to go through"),
    "逛": ("guàng", "to stroll"),
    "速": ("sù", "fast"),
    "造": ("zào", "to make"),
    "遇": ("yù", "to meet"),
    "遍": ("biàn", "everywhere"),
    "道": ("dào", "road"),
    "遭": ("zāo", "to meet by chance (usually with misfortune)"),
    "遮": ("zhē", "to cover up (a shortcoming)"),
    "遵": ("zūn", "to observe"),
    "避": ("bì", "to avoid"),
    "邀": ("yāo", "to invite"),
    "邮": ("yóu", "post (office)"),
    "邻": ("lín", "neighbor"),
    "部": ("bù", "ministry"),
    "配": ("pèi", "to join"),
    "酒": ("jiǔ", "wine (esp. rice wine)"),
    "酸": ("suān", "sour"),
    "醒": ("xǐng", "to wake up"),
    "释": ("shì", "to explain"),
    "野": ("yě", "wild/field"),
    "量": ("liàng", "capacity"),
    "金": ("jīn", "gold/metal"),
    "针": ("zhēn", "needle"),
    "钓": ("diào", "to fish with a hook and bait"),
    "钞": ("chāo", "money"),
    "钟": ("zhōng", "handleless cup"),
    "钢": ("gāng", "steel"),
    "钻": ("zuān", "to drill"),
    "铁": ("tiě", "iron (metal)"),
    "铃": ("líng", "CL:隻|只[zhi1]"),
    "铜": ("tóng", "copper (chemistry)"),
    "银": ("yín", "silver"),
    "链": ("liàn", "chain"),
    "销": ("xiāo", "to melt (metal)"),
    "锅": ("guō", "pot"),
    "错": ("cuò", "mistake"),
    "锤": ("chuí", "hammer"),
    "键": ("jiàn", "key (on a piano or computer keyboard)"),
    "锻": ("duàn", "to forge"),
    "镇": ("zhèn", "to press down"),
    "镜": ("jìng", "mirror"),
    "闪": ("shǎn", "to dodge"),
    "闭": ("bì", "to close"),
    "闯": ("chuǎng", "to rush"),
    "闲": ("xián", "enclosure"),
    "闷": ("mèn", "bored"),
    "闹": ("nào", "noisy"),
    "闻": ("wén", "to hear"),
    "阅": ("yuè", "to inspect"),
    "阔": ("kuò", "rich"),
    "队": ("duì", "squadron"),
    "防": ("fáng", "to protect"),
    "阴": ("yīn", "overcast (weather)"),
    "阵": ("zhèn", "disposition of troops"),
    "阻": ("zǔ", "to hinder"),
    "附": ("fù", "to add"),
    "际": ("jì", "border"),
    "陆": ("lù", "shore"),
    "陈": ("chén", "to display; (surname)"),
    "降": ("jiàng", "to drop"),
    "限": ("xiàn", "limit"),
    "院": ("yuàn", "courtyard"),
    "除": ("chú", "to get rid of"),
    "险": ("xiǎn", "danger"),
    "陪": ("péi", "to accompany"),
    "随": ("suí", "to follow"),
    "隐": ("yǐn", "secret"),
    "隔": ("gé", "to separate"),
    "难": ("nán", "difficult (to...)"),
    "雄": ("xióng", "male"),
    "集": ("jí", "to gather"),
    "雪": ("xuě", "snow"),
    "零": ("líng", "zero"),
    "雾": ("wù", "fog"),
    "需": ("xū", "to require"),
    "震": ("zhèn", "to shake"),
    "露": ("lù", "dew"),
    "静": ("jìng", "still"),
    "非": ("fēi", "to not be"),
    "靠": ("kào", "to lean against or on"),
    "鞋": ("xié", "shoe"),
    "音": ("yīn", "sound"),
    "页": ("yè", "page"),
    "顶": ("dǐng", "apex"),
    "项": ("xiàng", "back of neck"),
    "顺": ("shùn", "to obey"),
    "须": ("xū", "must"),
    "顽": ("wán", "mischievous"),
    "顾": ("gù", "to look after"),
    "顿": ("dùn", "to stop"),
    "预": ("yù", "to advance"),
    "领": ("lǐng", "neck"),
    "颈": ("jǐng", "neck"),
    "颗": ("kē", "measure word for small round things"),
    "题": ("tí", "topic"),
    "颜": ("yán", "color"),
    "额": ("é", "forehead"),
    "飘": ("piāo", "to float"),
    "食": ("shí", "to eat"),
    "餐": ("cān", "meal"),
    "饮": ("yǐn", "to drink"),
    "饺": ("jiǎo", "dumplings with meat filling"),
    "馆": ("guǎn", "building"),
    "首": ("shǒu", "head"),
    "驾": ("jià", "to harness"),
    "骄": ("jiāo", "proud"),
    "验": ("yàn", "to examine"),
    "骑": ("qí", "to sit astride"),
    "骗": ("piàn", "to cheat"),
    "骨": ("gǔ", "bone"),
    "鬼": ("guǐ", "ghost"),
    "魔": ("mó", "devil"),
    "鲜": ("xiān", "fresh"),
    "鹅": ("é", "goose"),
    "鹰": ("yīng", "eagle"),
    "鹿": ("lù", "deer"),
    "麻": ("má", "hemp"),
    "黄": ("huáng", "yellow"),
    "默": ("mò", "silent"),
    "鼓": ("gǔ", "drum"),
    "鼠": ("shǔ", "rat"),
    "鼻": ("bí", "nose"),
    "齐": ("qí", "neat"),
    "龄": ("líng", "age"),
    "龙": ("lóng", "dragon"),
    "龟": ("guī", "tortoise"),
}
